print('New ID Badge')
print('------------')
first_name = input('[state your first name]')
last_name = input('[state your last name]')
E_mail = input ('[state your email]')
phone_number = input('[type your phone number]')
Job_title = input('[state your Job title]')
ID_number= input ('[state your ID number]')
eye_color= input('[please input your eye color]')
hair_color=input('input your hair color')
month=input ('[input birth month]')
training=input('[have you had training?]')

#all the questions

print('ID processed ')
print('------------')
print('Awesome INc. ID processed')
print('------------')
print(f'Name:{first_name}{last_name}')
print(f'Email:{E_mail}')
print('-------------- ')
print(f'Phone:{phone_number}')
print(f'Job title:{Job_title}')
print(f'ID number:{ID_number}')
print('--------------------')
print(f'[Eye color]:{eye_color}'    f'[hair color]:{hair_color}')     
print(f'[month]:{month}'       f'[training]:{training}')
